# The Timed Version of the Plactic Monoid
## By Amritanshu Prasad

This worksheet illustrates our results on timed words with examples and verifications of theorems.


### Section 3.1: Timed Tableaux

#### Timed Word

The class ``TimedWord`` is is for timed words. The word $c_1^{t_1}\dotsb c_k^{t_k}$ is constrcuted as ``[(c1,t1), (c2,t2),...(ck,tk)]``.

The timed word from **Example 3.1.4** is constructed below:

In [1]:
%run timed_tableau.py
w = TimedWord([(3,0.8), (4, 1.1), (1,1.4), (2,1.6), (3,0.7)])
print w

[[3, 0.8], [4, 1.1], [1, 1.4], [2, 1.6], [3, 0.7]]


This timed word is a timed tableau:

In [2]:
w.is_tableau()

True

``random_word(max_let, terms, max_time=1)``
constructs a random timed word with maximum letter ``max_let``, ``terms`` many terms, and each term having maximum length ``max_term``.

In [3]:
w = random_word(5, 3); print w # This word will have 3 terms.

[[1, 0.6023272835701944], [5, 0.19040307281385271], [4, 0.6742914739316462]]


#### Timed Row

``TimedRow`` is derived from the class ``TimedWord``. For example:

In [4]:
r = TimedRow([(1,0.3), (2, 0.1), (5, 0.2)]); print r

[[1, 0.3], [2, 0.1], [5, 0.2]]


``random_row(max_let, max_time=1)`` constructs a random row with maximum letter ``max_let``. Each term has maximum length ``max_term``.

In [5]:
r = random_row(5); print r

[[1, 0.0604963171846048], [2, 0.29875912651014935], [3, 0.8465528521624526], [4, 0.7968301609881252], [5, 0.003389899592006196]]


### Section 3.2
#### ROWINS (Definition 3.2.1 and Example 3.2.2)
 A row can be inserted into another:

In [6]:
u = TimedRow([(1,1.4),(2,1.6),(3,0.7)])
v = TimedRow([(1,0.7),(2,0.2)])
print u.insert_row(v)

([[2, 0.7], [3, 0.2]], [[1, 2.0999999999999996], [2, 1.1], [3, 0.49999999999999994]])


#### INSERT (Definition 3.2.3 and Example 3.2.4):

In [7]:
w = TimedTableau([(3,0.8), (4, 1.1), (1,1.4), (2,1.6), (3,0.7)])
w.insert_row(TimedRow([(1,0.7),(2,0.2)]))

[[3, 0.7], [4, 0.2], [2, 0.7], [3, 0.3000000000000001], [4, 0.9000000000000001], [1, 2.0999999999999996], [2, 1.1], [3, 0.49999999999999994]]

#### Insertion Tableau (Definition 3.2.7 and Example 3.2.8)

In [8]:
w = TimedWord([(3, 0.8), (1, 0.5), (4, 1.1), (1, 0.9), (2, 1.6), (3, 0.7), (1, 0.7), (2, 0.2)])
w.insertion_tableau()

[[3, 0.7], [4, 0.2], [2, 0.7], [3, 0.3000000000000001], [4, 0.9000000000000001], [1, 2.0999999999999996], [2, 1.1], [3, 0.49999999999999994]]

#### Schuetzenberger involution on word (Definition 3.2.9)

In [9]:
print w
u = w.schuetzenberger_involution(); print u

[[3, 0.8], [1, 0.5], [4, 1.1], [1, 0.9], [2, 1.6], [3, 0.7], [1, 0.7], [2, 0.2]]
[[3, 0.2], [4, 0.7], [2, 0.7], [3, 1.6], [4, 0.9], [1, 1.1], [4, 0.5], [2, 0.8]]


Note that ``w`` and ``u`` have insertion tableau of the same shape (this can be deduced from **Greene's theorem (Theorem 3.6.1)**.

In [10]:
print w.insertion_tableau().shape()
print u.insertion_tableau().shape()

[3.6999999999999997, 1.9000000000000001, 0.8999999999999999]
[3.6999999999999997, 1.9000000000000001, 0.8999999999999999]


#### Randomized verification of Lemma 3.2.1

First prepare random rows $u$ and $v$ such that $(v',u')=ROWINS(u,v)$, then $l(v')=l(v)$.
This is done by first choosing random rows $u$ and $v$, computing $(x,y)=ROWINS(u,v)$, and then truncating $v$ to $l(x)$.

In [11]:
u = random_row(5)
v = random_row(5)
vv, uu = u.insert_row(v)
v=v.truncate(vv.length())
vv, uu = u.insert_row(v)
print vv.length() == v.length()

True


Now we verify **Lemma 3.2.1** using $u$ and $v$ that have been prepared in this way: 

In [12]:
r, s = uu.schuetzenberger_involution(max_let=5).insert_row(vv.schuetzenberger_involution(max_let=5))
print s.schuetzenberger_involution() == u
print r.schuetzenberger_involution() == v

True
True


#### Randomized verification of the proof of Corollary 3.2.11

In [13]:
n = 2 # pick largest letter of alphabet
u = random_row(n)
v = random_row(n)
vv, uu = u.insert_row(v)
r = u.length()
x, y = inverse_rowins(vv, uu, r) # implemented using proof of Corollary 3.2.11
print u == x and v == y

True


#### Randomized verification of the Deletion algorithm (Definition 3.2.13)

In [14]:
w = random_word(5, 5).insertion_tableau()
r = random_row(5)
ww = w.insert_row(r)
v, u = delete(ww, w.shape())
print u == w and v == r

True


### Section 4.1
#### Illustration of Real RSK (and that $P$ and $Q$ have the same shape- Theorem 4.1.2)

In [15]:
A = random_real_matrix(3, 4)
P, Q = real_rsk(A)
print "The Matrix A:\n", A
print "The tableau P:\n", P
print "The tableau Q:\n", Q
from numpy import allclose, array
print allclose(array(P.shape()), array(Q.shape())) # Check that P and Q have same shape

The Matrix A:
[[ 0.67779294  0.9221423   0.15711772  0.25277145]
 [ 0.95114946  0.13640205  0.77579964  0.92088717]
 [ 0.30953467  0.65774211  0.7543032   0.08182725]]
The tableau P:
[[3, 0.13640205433000474], [4, 0.25277145400863288], [2, 1.0585443496680864], [3, 0.79651530397686232], [4, 0.80937828274101453], [1, 1.9384770660369046], [2, 0.65774211047995745], [3, 0.75430319650161504], [4, 0.19333613777488079]]
The tableau Q:
[[3, 0.38917350833863762], [2, 1.3320314647407967], [3, 1.3324064716451667], [1, 2.0098243999561789], [2, 1.4522068626890046], [3, 0.081827248148174658]]
True


#### Randomized verification of algorithm for inverse of real RSK (see proof of Theorem 4.1.2)

In [16]:
A = random_real_matrix(3,2)
P, Q = real_rsk(A)
print allclose(inverse_real_rsk(P, Q),A) # verifies that A is recovered by inverse of RSK
                                         # (implemented using the proof of Theorem 4.1.2)

True
