# The Timed Version of the Plactic Monoid
## By Amritanshu Prasad

This worksheet illustrates our results on timed words with examples and verifications of theorems.


### Section 3.1: Timed Tableaux

#### Timed Word

The class ``TimedWord`` is is for timed words. The word $c_1^{t_1}\dotsb c_k^{t_k}$ is constrcuted as ``[(c1,t1), (c2,t2),...(ck,tk)]``.

The timed word from **Example 2.1.6** is constructed below:

In [1]:
%run timed_tableau.py
w = TimedWord([(3,0.8), (4, 1.1), (1,1.4), (2,1.6), (3,0.7)])
print w

[[3, 0.8], [4, 1.1], [1, 1.4], [2, 1.6], [3, 0.7]]


This timed word is a timed tableau:

In [2]:
print w.is_tableau()
print w.shape()
print w.weight()

True
[3.7, 1.9000000000000001]
[1.4, 1.6, 1.5, 1.1]


``random_word(max_let, terms, max_time=1)``
constructs a random timed word with maximum letter ``max_let``, ``terms`` many terms, and each term having maximum length ``max_term``.

In [3]:
w = random_word(5, 3); print w # This word will have 3 terms.

[[1, 0.4992655451209097], [4, 1.537576980213973]]


#### Timed Row

``TimedRow`` is derived from the class ``TimedWord``. For example:

In [4]:
r = TimedRow([(1,0.3), (2, 0.1), (5, 0.2)]); print r

[[1, 0.3], [2, 0.1], [5, 0.2]]


``random_row(max_let, max_time=1)`` constructs a random row with maximum letter ``max_let``. Each term has maximum length ``max_term``.

In [5]:
r = random_row(5); print r

[[1, 0.06304238349993319], [2, 0.5175618506713436], [3, 0.6023953315643266], [4, 0.7730532547063089], [5, 0.7340601674106371]]


#### ROWINS (Definition 2.2.1 and Example 2.2.2)
 A row can be inserted into another:

In [6]:
u = TimedRow([(1,1.4),(2,1.6),(3,0.7)])
v = TimedRow([(1,0.7),(2,0.2)])
print u.insert_row(v)

([[2, 0.7], [3, 0.2]], [[1, 2.0999999999999996], [2, 1.1], [3, 0.49999999999999994]])


#### INSERT (Definition 2.2.3 and Example 2.2.4):

In [7]:
w = TimedTableau([(3,0.8), (4, 1.1), (1,1.4), (2,1.6), (3,0.7)])
w.insert_row(TimedRow([(1,0.7),(2,0.2)]))

[[3, 0.7], [4, 0.2], [2, 0.7], [3, 0.3000000000000001], [4, 0.9000000000000001], [1, 2.0999999999999996], [2, 1.1], [3, 0.49999999999999994]]

#### Insertion Tableau (Definition 2.2.7 and Example 2.2.8)

In [8]:
w = TimedWord([(3, 0.8), (1, 0.5), (4, 1.1), (1, 0.9), (2, 1.6), (3, 0.7), (1, 0.7), (2, 0.2)])
w.insertion_tableau()

[[3, 0.7], [4, 0.2], [2, 0.7], [3, 0.3000000000000001], [4, 0.9000000000000001], [1, 2.0999999999999996], [2, 1.1], [3, 0.49999999999999994]]

#### Schuetzenberger involution on word (Definition 2.2.9)

In [9]:
print w
u = w.schuetzenberger_involution(); print u
w == u.schuetzenberger_involution()

[[3, 0.8], [1, 0.5], [4, 1.1], [1, 0.9], [2, 1.6], [3, 0.7], [1, 0.7], [2, 0.2]]
[[3, 0.2], [4, 0.7], [2, 0.7], [3, 1.6], [4, 0.9], [1, 1.1], [4, 0.5], [2, 0.8]]


True

Note that ``w`` and ``u`` have insertion tableau of the same shape (this can be deduced from **Greene's theorem (Theorem 3.4.1)**.

In [10]:
print w.insertion_tableau().shape()
print u.insertion_tableau().shape()

[3.6999999999999997, 1.9000000000000001, 0.8999999999999999]
[3.6999999999999997, 1.9000000000000001, 0.8999999999999999]


#### Randomized verification of Lemma 2.2.10

First prepare random rows $u$ and $v$ such that $(v',u')=ROWINS(u,v)$, then $l(v')=l(v)$.
This is done by first choosing random rows $u$ and $v$, computing $(x,y)=ROWINS(u,v)$, and then truncating $v$ to $l(x)$.

In [11]:
u = random_row(5)
v = random_row(5)
vv, uu = u.insert_row(v)
v=v.truncate(vv.length())
vv, uu = u.insert_row(v)
print vv.length() == v.length()

True


Now we verify **Lemma 2.2.10** using $u$ and $v$ that have been prepared in this way: 

In [12]:
r, s = uu.schuetzenberger_involution(max_let=5).insert_row(vv.schuetzenberger_involution(max_let=5))
print s.schuetzenberger_involution() == u
print r.schuetzenberger_involution() == v

True
True


#### Randomized verification of the proof of Corollary 2.2.11

In [13]:
n = 2 # pick largest letter of alphabet
u = random_row(n)
v = random_row(n)
vv, uu = u.insert_row(v)
r = u.length()
x, y = inverse_rowins(vv, uu, r) # implemented using proof of Corollary 3.2.11
print u == x and v == y

True


#### Randomized verification of the Deletion algorithm (Definition 2.2.13)

In [14]:
w = random_word(5, 5).insertion_tableau()
r = random_row(5)
ww = w.insert_row(r)
v, u = delete(ww, w.shape())
print u == w and v == r

True


### Section 4.1
#### Illustration of Real RSK (and that $P$ and $Q$ have the same shape- Theorem 5.1.2)

In [15]:
A = random_real_matrix(3, 4)
P, Q = real_rsk(A)
print "The Matrix A:\n", A
print "The tableau P:\n", P
print "The tableau Q:\n", Q
from numpy import allclose, array
print allclose(array(P.shape()), array(Q.shape())) # Check that P and Q have same shape

The Matrix A:
[[ 0.87123741  0.36724386  0.31042644  0.94255563]
 [ 0.73628799  0.6093566   0.73989132  0.53609957]
 [ 0.67454959  0.28221894  0.88963217  0.99732108]]
The tableau P:
[[3, 0.31042644399208397], [4, 0.64634208937278059], [2, 0.97660046391371502], [3, 0.34741193431604689], [4, 0.83231311621830062], [1, 2.2820749975013883], [2, 0.28221893913417562], [3, 1.2821115524510809], [4, 0.99732108134302788]]
The tableau Q:
[[3, 0.95676853336486456], [2, 1.6202259417598683], [3, 0.53609957268819408], [1, 2.4914633509459323], [2, 1.0014095453642957], [3, 1.3508536741194452]]
True


#### Randomized verification of algorithm for inverse of real RSK (see proof of Theorem 5.1.2)

In [16]:
A = random_real_matrix(3,2)
P, Q = real_rsk(A)
print allclose(inverse_real_rsk(P, Q),A) # verifies that A is recovered by inverse of RSK
                                         # (implemented using the proof of Theorem 4.1.2)

True
