In [1]:
%run timed_tableau.py

# The Timed Version of the Plactic Monoid
## By Amritanshu Prasad

This worksheet illustrates our results on timed words with examples and verifications of theorems.


### Section 3.1: Timed Tableaux

#### Timed Word

The class ``TimedWord`` is is for timed words. The word $c_1^{t_1}\dotsb c_k^{t_k}$ is constrcuted as ``[(c1,t1), (c2,t2),...(ck,tk)]``.

The timed word from **Example 3.1.4** is constructed below:

In [2]:
w = TimedWord([(3,0.8), (4, 1.1), (1,1.4), (2,1.6), (3,0.7)])
print w

[[3, 0.8], [4, 1.1], [1, 1.4], [2, 1.6], [3, 0.7]]


This timed word is a timed tableau:

In [3]:
w.is_tableau()

True

``random_word(max_let, terms, max_time=1)``
constructs a random timed word with maximum letter ``max_let``, ``terms`` many terms, and each term having maximum length ``max_term``.

In [4]:
w = random_word(5, 3); print w # This word will have 3 terms.

[[4, 0.0795522506239349], [2, 0.6009561626080826], [1, 0.6508700502959133]]


#### Timed Row

``TimedRow`` is derived from the class ``TimedWord``. For example:

In [5]:
r = TimedRow([(1,0.3), (2, 0.1), (5, 0.2)]); print r

[[1, 0.3], [2, 0.1], [5, 0.2]]


``random_row(max_let, max_time=1)`` constructs a random row with maximum letter ``max_let``. Each term has maximum length ``max_term``.

In [6]:
r = random_row(5); print r

[[1, 0.2298253798869453], [2, 0.3281705709230045], [3, 0.5184539376255008], [4, 0.23248160247793026], [5, 0.059064983056283826]]


#### ROWINS (Definition 3.2.1 and Example 3.2.2)
 A row can be inserted into another:

In [7]:
u = TimedRow([(1,1.4),(2,1.6),(3,0.7)])
v = TimedRow([(1,0.7),(2,0.2)])
print u.insert_row(v)

([[2, 0.7], [3, 0.2]], [[1, 2.0999999999999996], [2, 1.1], [3, 0.49999999999999994]])


#### INSERT (Definition 3.2.3 and Example 3.2.4):

In [8]:
w = TimedTableau([(3,0.8), (4, 1.1), (1,1.4), (2,1.6), (3,0.7)])
w.insert_row(TimedRow([(1,0.7),(2,0.2)]))

[[3, 0.7], [4, 0.2], [2, 0.7], [3, 0.3000000000000001], [4, 0.9000000000000001], [1, 2.0999999999999996], [2, 1.1], [3, 0.49999999999999994]]

#### Insertion Tableau (Definition 3.2.7 and Example 3.2.8)

In [9]:
w = TimedWord([(3, 0.8), (1, 0.5), (4, 1.1), (1, 0.9), (2, 1.6), (3, 0.7), (1, 0.7), (2, 0.2)])
w.insertion_tableau()

[[3, 0.7], [4, 0.2], [2, 0.7], [3, 0.3000000000000001], [4, 0.9000000000000001], [1, 2.0999999999999996], [2, 1.1], [3, 0.49999999999999994]]

#### Schuetzenberger involution on word (Definition 3.2.9)

In [10]:
print w
u = w.schuetzenberger_involution(); print u

[[3, 0.8], [1, 0.5], [4, 1.1], [1, 0.9], [2, 1.6], [3, 0.7], [1, 0.7], [2, 0.2]]
[[3, 0.2], [4, 0.7], [2, 0.7], [3, 1.6], [4, 0.9], [1, 1.1], [4, 0.5], [2, 0.8]]


Note that ``w`` and ``u`` have insertion tableau of the same shape (this can be deduced from **Greene's theorem (Theorem 3.6.1)**.

In [11]:
print w.insertion_tableau().shape()
print u.insertion_tableau().shape()

[3.6999999999999997, 1.9000000000000001, 0.8999999999999999]
[3.6999999999999997, 1.9000000000000001, 0.8999999999999999]


#### Randomized verification of Lemma 3.2.1

First prepare random rows $u$ and $v$ such that $(v',u')=ROWINS(u,v)$, then $l(v')=l(v)$.
This is done by first choosing random rows $u$ and $v$, computing $(x,y)=ROWINS(u,v)$, and then truncating $v$ to $l(x)$.

In [36]:
u = random_row(5)
v = random_row(5)
vv, uu = u.insert_row(v)
v=v.truncate(vv.length())
vv, uu = u.insert_row(v)
print vv.length() == v.length()

True


Now we verify **Lemma 3.2.1** using $u$ and $v$ that have been prepared in this way: 

In [37]:
r, s = uu.schuetzenberger_involution(max_let=5).insert_row(vv.schuetzenberger_involution(max_let=5))
print s.schuetzenberger_involution() == u
print r.schuetzenberger_involution() == v

True
True


#### Randomized verification of the proof of Corollary 3.2.11    

In [89]:
n = 6 # pick largest letter of alphabet
u = random_row(n)
v = random_row(n)
vv, uu = u.insert_row(v)
r = u.length()
x, y = inverse_rowins(vv, uu, r) # implemented using proof of Corollary 3.2.11
print u == x and v == y

True


In [46]:
print u, u.time_stamps()

[[1, 0.7703056957469098], [2, 0.7906429482504347], [3, 0.9139535092317261], [4, 0.2273060213838578], [5, 0.653290064204562]] [0, 0.7703056957469098, 1.5609486439973446, 2.4749021532290705, 2.7022081746129283]


In [36]:
w = random_word(10, 5)

In [37]:
w

[[7, 0.9451434368989666], [8, 0.3794956986630452], [6, 0.22426025692438223], [10, 0.24715379800931037], [4, 0.011073822432015601]]

In [38]:
w.subword([[0,1.2]]) == w.truncate(1.2)

True

In [7]:
w.concatenate(w)

[[7, 0.1181465564848031], [9, 0.7998146393680998], [7, 0.33242863048659843], [3, 0.18624329285410568], [1, 0.6744423378155662], [7, 0.1181465564848031], [9, 0.7998146393680998], [7, 0.33242863048659843], [3, 0.18624329285410568], [1, 0.6744423378155662]]

In [8]:
TimedWord([]).concatenate(w)

[[7, 0.1181465564848031], [9, 0.7998146393680998], [7, 0.33242863048659843], [3, 0.18624329285410568], [1, 0.6744423378155662]]

#### Illustration of Real RSK (and that $P$ and $Q$ have the same shape- Theorem 4.1.2)

In [81]:
%run timed_tableau.py
A = random_real_matrix(3, 4)
print A
P, Q = real_rsk(A)
print P
print Q
print numpy.allclose(numpy.array(P.shape()), numpy.array(Q.shape()))

[[ 0.95617508  0.25065884  0.31787227  0.45252542]
 [ 0.84786644  0.75127168  0.35656618  0.61276414]
 [ 0.99179516  0.37620484  0.04765051  0.53639277]]
[[3, 0.31787227447918398], [4, 0.45252541630188459], [2, 1.0019305152636262], [3, 0.35656618150599395], [4, 0.30781264496726746], [1, 2.795836668721603], [2, 0.37620484199896753], [3, 0.047650505038922097], [4, 0.84134426645371541]]
[[3, 0.77039769078106846], [2, 1.0210565283237552], [3, 0.64525281341313256], [1, 1.977231604308813], [2, 1.5474119044820747], [3, 0.53639277342232028]]
True


In [75]:
P.rows()

[[[3, 0.0095768582993116524], [4, 0.089386754318420025]],
 [[2, 0.21047912014536585], [3, 0.20383497966456221], [4, 0.6455037838933706]],
 [[1, 1.5658088991341335], [2, 0.014549169229123415], [3, 0.24901358239258731], [4, 0.55908915590565866]]]

In [79]:
w

[[7, 0.9451434368989666], [8, 0.3794956986630452], [6, 0.22426025692438223], [10, 0.24715379800931037], [4, 0.011073822432015601]]